### PR TITLE
Update creating-new-entities.md

### PR DESCRIPTION
**Pull request by aliaspooryorik**
Added hint about using populateFromStruct for all properties.
Removed incorrect fill method description

### CODE REVIEW

**Comment by elpete** [comment]
Can you help me understand why you would need to set other properties?

**Comment by aliaspooryorik** [comment]
I personally wouldn't :) 

It came up in a discussion about the behaviour of ColdBox `populate` vs what Quick does. They have the same name but different behaviour so was to clear that up really. There may be confusion if for example moving from cbORM to Quick.

There are some people who for example would want to have a user entity which has username and password. For those you have properties, but you may also have a 'confirmpassword' value that you want to validate matches the password but do not want to persist. To me that is not the job of the entity (it handles persistence) but others may want to treat the entity as a business object which happens to also do persistence.

**Comment by elpete** [comment]
Hmmm…didn’t mean to close it. I was trying to update the docs branch to the latest (7.0.0)

**Comment by aliaspooryorik** [comment]
Not sure I can reopen it - will see if I can find a way.

**Pull request closed without merging**
